[package]
name = "pokus-rocket"
version = "0.0.0"
# workspace = "./"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
